site_name: B/Y Colors
site_url: https://colors.kyrylo.gr/
repo_url: https://github.com/kyrylo-gr/b-y-colors
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.ico
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
extra_css:
  - assets/mkdocs.css

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              returns_type_in_property_summary: true
            inherited_members: true
            filters:
              - '!^_' # exclude all members starting with _
              - '^__init__$' # but always include __init__ modules and methods
              - '^__new__$' # but always include __new__ methods
              - '^__getitem__$'
              - '^__setitem__$'
            show_source: true
            show_submodules: true
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: true
            show_object_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table
            # members_order: source
            show_signature: true
            show_signature_annotations: false
            separate_signature: true
            unwrap_annotated: true
      watch: python/bycolors/

nav:
  - ColorClass: python/
  - All colors: /index.html
  - Cmaps: python/cmap/
